name = "botblock-api-worker"
type = "javascript"
account_id = "fb1f542488f2441acf88ca15f3a8390d"
workers_dev = true
compatibility_date = "2021-10-17"
kv_namespaces = [
    { binding = "RATELIMIT", id = "075636ba3f0f4d81b1dd2569177a98e9", preview_id = "075636ba3f0f4d81b1dd2569177a98e9" }
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.staging]
zone_id = "ccea9c3e6518bf407939c5493a122423"
workers_dev = false
route = "staging.botblock.org/api/*"
kv_namespaces = [
    { binding = "RATELIMIT", id = "17c7991d3811406ca22d6329b17792b4" }
]
